version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform
        environment:
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run:
          name: Create fake SSH public key
          command: mkdir -p ~/.ssh && touch ~/.ssh/id_rsa.pub
      - run:
          name: Create Terraform variables file
          command: cd terraform/env && cp terraform.tfvars.example terraform.tfvars
      - run:
          name: Set up Terraform
          command: cd terraform/env && terraform init -backend=false
      - run:
          name: Validate Terraform
          command: cd terraform/env && terraform validate
