version: 2
jobs:
  packer:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Validate Packer template
          command: packer validate -syntax-only packer.json

  terraform:
    docker:
      - image: hashicorp/terraform
        environment:
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run:
          name: Create fake SSH public key
          command: mkdir -p ~/.ssh && touch ~/.ssh/id_rsa.pub

      - run:
          name: mgmt - Set up Terraform
          command: cd terraform/mgmt && terraform init -backend=false
      - run:
          name: mgmt - Validate Terraform
          command: cd terraform/mgmt && terraform validate

      - run:
          name: env - Create Terraform variables file
          command: cd terraform/env && cp terraform.tfvars.example terraform.tfvars
      - run:
          name: env - Set up Terraform
          command: cd terraform/env && terraform init -backend=false
      - run:
          name: env - Validate Terraform
          command: cd terraform/env && terraform validate

workflows:
  version: 2

  validate:
    jobs:
      - packer
      - terraform
