version: 2
jobs:
  ansible:
    docker:
      - image: williamyeh/ansible:alpine3
    steps:
      - checkout
      - run:
          name: Install Ansible dependencies
          command: apk add --no-cache git
      - run:
          name: Download Ansible dependencies
          command: ansible-galaxy install -p ansible/roles -r ansible/requirements.yml
      - persist_to_workspace:
          # doesn't allow the full directory to be persisted, so only save the roles
          # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
          root: ansible/roles
          paths:
            - ./*

  packer:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Validate Jenkins template
          command: packer validate -syntax-only packer/jenkins.json
      - run:
          name: Validate WordPress template
          command: packer validate -syntax-only packer/wordpress.json

  terraform:
    docker:
      - image: hashicorp/terraform
        environment:
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - attach_workspace:
          at: ansible/roles

      - run:
          name: Create fake SSH public key
          command: mkdir -p ~/.ssh && touch ~/.ssh/id_rsa.pub

      - run:
          name: mgmt - Set up Terraform
          command: cd terraform/mgmt && terraform init -backend=false
      - run:
          name: mgmt - Validate Terraform
          command: cd terraform/mgmt && terraform validate

      - run:
          name: env - Create Terraform variables file
          command: cd terraform/env && cp terraform.tfvars.example terraform.tfvars
      - run:
          name: env - Set up Terraform
          command: cd terraform/env && terraform init -backend=false
      - run:
          name: env - Validate Terraform
          command: cd terraform/env && terraform validate

workflows:
  version: 2

  validate:
    jobs:
      - ansible
      - packer
      - terraform:
          requires:
            - ansible
