version: 2
jobs:
  validate_packer:
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout
      - run:
          name: Validate WordPress template
          command: packer validate -syntax-only packer/wordpress.json

  validate_terraform:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Create fake SSH public key
          command: mkdir -p ~/.ssh && touch ~/.ssh/id_rsa.pub

      - run:
          name: bootstrap - Set up Terraform
          command: cd terraform/bootstrap && terraform init -backend=false -input=false
      - run:
          name: bootstrap - Validate Terraform
          command: cd terraform/bootstrap && terraform validate

      - run:
          name: mgmt - Create Terraform variables file
          command: cd terraform/mgmt && cp terraform.tfvars.example terraform.tfvars
      - run:
          name: mgmt - Set up Terraform
          command: cd terraform/mgmt && terraform init -backend=false -input=false
      - run:
          name: mgmt - Validate Terraform
          command: cd terraform/mgmt && terraform validate

      - run:
          name: env - Set up Terraform
          command: cd terraform/env && terraform init "-backend-config=bucket=$TF_ENV_BUCKET" -input=false
      - run:
          name: env - Validate Terraform
          command: cd terraform/env && terraform validate
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  deploy_env:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys
      - run:
          name: Disable host key checking
          command: printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

      - run:
          name: Bootstrap the environment
          command: terraform apply -input=false -auto-approve -target=aws_route53_record.db
          working_directory: ~/project/terraform/env

      # this command fails if the requirements.yml is empty
      # - run:
      #     name: Download Ansible dependencies
      #     command: ansible-galaxy install -p ansible/roles -r ansible/requirements.yml

      - run:
          name: Build WordPress AMI
          command: |
            packer build \
              -var db_host=$(terraform output db_host) \
              -var db_name=$(terraform output db_name) \
              -var db_user=$(terraform output db_user) \
              -var "db_pass=${TF_VAR_db_pass}" \
              ../../packer/wordpress.json
          working_directory: ~/project/terraform/env

      - run:
          name: Deploy the full environment
          command: terraform apply -input=false -auto-approve
          working_directory: ~/project/terraform/env

workflows:
  version: 2

  validate_and_deploy:
    jobs:
      - validate_packer
      - validate_terraform
      - deploy_env:
          filters:
            branches:
              only: master
          requires:
            - validate_packer
            - validate_terraform
