---
- hosts: jenkins
  become: true
  roles:
    - gsa.jenkins
    - role: cristian04.cloudwatch-monitoring
      cron_specs:
        - name: "Cloudwatch monitoring"
          minute: "*/5"
          hour: "*"
          job: "{{ cloud_watch_monitoring_path }}/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --swap-util --swap-used --disk-space-util --disk-path={{ path }} --disk-space-avail --from-cron"